version: "3.9"
services:
  api:
    build: ./Api
    depends_on:
      identityserver:
        condition: service_started
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet Api.dll"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5003;http://+:5002
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
      - AUTHENTICATION__AUTHORITY=https://identityserver:5001
    ports:
      - "5002:5002"
      - "5003:5003"
    volumes:
      - ./localhost.pfx:/https/localhost.pfx:ro
      - ./localhost.crt:/usr/local/share/ca-certificates/localhost.crt:ro
  db:
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  identityserver:
    build: ./IdentityServer
    depends_on:
      db:
        condition: service_healthy
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet IdentityServer.dll"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
      - CONNECTIONSTRINGS__DEFAULTCONNECTION=Server=db;Port=5432;Database=identityserver;User Id=postgres;Password=password;
      - WEBAPPLICATIONURL=https://webapplication:5005
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./localhost.pfx:/https/localhost.pfx:ro
      - ./localhost.crt:/usr/local/share/ca-certificates/localhost.crt:ro
  webapplication:
    build: ./WebApplication
    depends_on:
      api:
        condition: service_started
      identityserver:
        condition: service_started
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet WebApplication.dll"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5005;http://+:5004
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
      - APIURL=https://api:5003
      - AUTHENTICATION__OPENIDCONNECT__AUTHORITY=https://identityserver:5001
    ports:
      - "5004:5004"
      - "5005:5005"
    volumes:
      - ./localhost.pfx:/https/localhost.pfx:ro
      - ./localhost.crt:/usr/local/share/ca-certificates/localhost.crt:ro
volumes:
  db:
