services:
  db:
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  webapplication:
    build:
      context: .
      dockerfile: ./WebApplication/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet WebApplication.dll"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=identity;User Id=postgres;Password=password;
      - Fido2__Origins__0=https://webapplication:7002
      - Fido2__ServerDomain=webapplication
      - Fido2__ServerName=webapplication
    ports:
      - "7002:8001"
    volumes:
      - ./localhost.pfx:/https/localhost.pfx:ro
      - ./localhost.crt:/usr/local/share/ca-certificates/localhost.crt:ro
volumes:
  db:
